### ISSUE TITLE
Empty turtle file after export

### ISSUE THREAD

**Issue by SvenLieber** [oSoc19/unshacled#165]
How to reproduce the behavior:

Open the app and press the *+Shape* button to create a node shape and then press the *+Property* button to create a property shape.
Then go to the menu and export the SHACL file as turtle.
The turtle file is empty.

It works for json.

**Comment by fbrckman** [comment]
As stated in #145: 
> In N3Serializer.serialize, jsonld.toRDF(model) returns an empty array in some cases. The model probably does not meet certain requirements. This is because ID's starting with a digit are treated as relative IRI's. Generated uuid's have a chance to start with a digit, causing them to be ignored since they are "invalid".

As of #198 (commit [944e221](https://github.com/oSoc19/unshacled/commit/944e221618fcdb28bce6801d50823c4eb1b1b42a)), ID's have to be valid IRI's to be accepted. This means that ID's cannot start with a digit anymore so that an empty Turtle file is no longer an issue.
