### ISSUE TITLE
Identifiers: standard? specification?

### ISSUE THREAD

**Issue by fbrckman** [oSoc19/unshacled#198]

**Comment by SvenLieber** [comment]
There exist different [best practices](http://patterns.dataincubator.org/book/identifier-patterns.html) in Linked Data to identify things.
The [patterned URI](http://patterns.dataincubator.org/book/patterned-uris.html) "pattern" for example suggests to use algorithmically constructred patterns like e.g. '/books/12345'. 

The [shared keys](http://patterns.dataincubator.org/book/shared-keys.html) pattern goes one step further and relies on the previously introduced "patterned URIs" and additionally using standard identifiers. The "MusicBrainz" platform they mention as example is based on [UUIDs](https://pubs.opengroup.org/onlinepubs/9629399/apdxa.htm) which are "unique across both space and time" 👩‍🚀 

Therefore I would suggest to follow that pattern, using `/shapes` as template and then a created UUID which can be done by e.g. using [this](https://www.npmjs.com/package/uuid) npm package.
So it would look something like this: `/shapes/123e4567-e89b-12d3-a456-426655440000`.

Then together with a base IRI (e.g. `http://example.org/ns/unshacled`) a shape is identified by something like this: `http://example.org/ns/unshacled/shapes/123e4567-e89b-12d3-a456-426655440000`.

We don't have to be too much worried about ID collisions, if someone else created the same UUID we still have our base IRI to distinguish. Additionally our users probably will use their own URI anyway and create something like https://data.vlaanderen.be/shacl/Begraafplaats-SHACL.ttl
