### ISSUE TITLE
Deleting data

### ISSUE THREAD

**Issue by SvenLieber** [oSoc19/unshacled#230]
I had the case that I worked with the example data.

Then I wanted to start a new example so I clicked on the *clear page* button, since I was not asked what I want to clear I assumed everything will be cleared.
However, only the shapes were cleared, not the data.

Although I can import new data, there is no way to remove the existing data from the data panel.

It would be nice if when clicking on the *clear page* button, there would be another sub-menu (or something similar) in which one can say what to remove, data, shapes or both. Maybe with some checkboxes and then a "are you sure" dialog.

**Comment by fbrckman** [comment]
Related: #179
